# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
print(np.__version__)


2.3.5


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [39]:
numpy_array = np.random.rand(2, 3, 5)
print(numpy_array)
numpy_array1 = np.random.random((2, 3, 5))
print(numpy_array1)
numpy_array2 = np.random.randn(2, 3, 5)
print(numpy_array1)
a = np.random.randint(0, 10, (2, 3, 5))
print(a)




[[[0.2209192  0.16135877 0.27831754 0.91442851 0.74344377]
  [0.40653357 0.47174424 0.11037924 0.86239929 0.2862934 ]
  [0.43451841 0.76331451 0.55478894 0.22972304 0.68982969]]

 [[0.1913436  0.97839633 0.3886416  0.88926748 0.40461357]
  [0.21675327 0.01330354 0.49875441 0.76114963 0.13636375]
  [0.78070825 0.31702904 0.60818119 0.70250719 0.1911373 ]]]
[[[0.0056127  0.63012355 0.11999992 0.31255118 0.16444723]
  [0.12218763 0.83195613 0.292421   0.10722832 0.33969585]
  [0.29752693 0.43641896 0.00762873 0.97867939 0.1064439 ]]

 [[0.61383374 0.57791079 0.68510098 0.30271729 0.26001795]
  [0.5133615  0.68599704 0.97343941 0.93786834 0.66469587]
  [0.88211088 0.0707     0.94700475 0.34495467 0.05375466]]]
[[[0.0056127  0.63012355 0.11999992 0.31255118 0.16444723]
  [0.12218763 0.83195613 0.292421   0.10722832 0.33969585]
  [0.29752693 0.43641896 0.00762873 0.97867939 0.1064439 ]]

 [[0.61383374 0.57791079 0.68510098 0.30271729 0.26001795]
  [0.5133615  0.68599704 0.97343941 0.93786834


### 4. Print a.


In [40]:
print(a)
print(np.shape(a))


[[[2 5 5 0 7]
  [0 7 1 5 8]
  [2 8 5 7 8]]

 [[4 6 9 4 5]
  [2 1 7 0 1]
  [8 7 8 8 9]]]
(2, 3, 5)


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [31]:
b = np.ones((5, 2, 3))




### 6. Print b.


In [41]:
print(b)
print(np.shape(b))


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
(5, 2, 3)



### 7. Do a and b have the same size? How do you prove that in Python code?


In [33]:
a.size == b.size


True


### 8. Are you able to add a and b? Why or why not?


In [37]:
a + b


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

The dimensions of a and be are different and we cannot add.



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [46]:
print(np.shape(b))
c = b.transpose((1,2,0))
print(np.shape(c))


(5, 2, 3)
(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
d = a + c

Now I am able to add a and c because the dimensions are same.


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [49]:
print(a)
print(d)



[[[2 5 5 0 7]
  [0 7 1 5 8]
  [2 8 5 7 8]]

 [[4 6 9 4 5]
  [2 1 7 0 1]
  [8 7 8 8 9]]]
[[[ 3.  6.  6.  1.  8.]
  [ 1.  8.  2.  6.  9.]
  [ 3.  9.  6.  8.  9.]]

 [[ 5.  7. 10.  5.  6.]
  [ 3.  2.  8.  1.  2.]
  [ 9.  8.  9.  9. 10.]]]


In terms of values one is integer and other is float.


### 12. Multiply a and c. Assign the result to e.


In [50]:
e = a * c
print(e)


[[[2. 5. 5. 0. 7.]
  [0. 7. 1. 5. 8.]
  [2. 8. 5. 7. 8.]]

 [[4. 6. 9. 4. 5.]
  [2. 1. 7. 0. 1.]
  [8. 7. 8. 8. 9.]]]




### 13. Does e equal to a? Why or why not?


In [51]:
np.shape(e) == np.shape(a)



True



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [52]:
d_min =np.min(d)
d_max =np.max(d)
d_mean =np.mean(d)
print(d_min, d_mean, d_max)



1.0 5.966666666666667 10.0



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [63]:
f = np.empty(d.shape)
print(f)

[[[ 25.  75.  75.   0.  75.]
  [  0.  75.  25.  75.  75.]
  [ 25.  75.  75.  75.  75.]]

 [[ 25.  75. 100.  25.  75.]
  [ 25.  25.  75.   0.  25.]
  [ 75.  75.  75.  75. 100.]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [64]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75
print(f)

[[[ 25.  75.  75.   0.  75.]
  [  0.  75.  25.  75.  75.]
  [ 25.  75.  75.  75.  75.]]

 [[ 25.  75. 100.  25.  75.]
  [ 25.  25.  75.   0.  25.]
  [ 75.  75.  75.  75. 100.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [65]:
print(d)
print(f)


[[[ 3.  6.  6.  1.  8.]
  [ 1.  8.  2.  6.  9.]
  [ 3.  9.  6.  8.  9.]]

 [[ 5.  7. 10.  5.  6.]
  [ 3.  2.  8.  1.  2.]
  [ 9.  8.  9.  9. 10.]]]
[[[ 25.  75.  75.   0.  75.]
  [  0.  75.  25.  75.  75.]
  [ 25.  75.  75.  75.  75.]]

 [[ 25.  75. 100.  25.  75.]
  [ 25.  25.  75.   0.  25.]
  [ 75.  75.  75.  75. 100.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [67]:
import numpy as np

a = np.random.choice([0, 25, 50, 75, 100], size=(2, 3, 5))

labels = {
    0: "A",
    25: "B",
    50: "C",
    75: "D",
    100: "E"
}

result = [[[labels[value] for value in row] for row in block] for block in a]
print(result)

[[['C', 'E', 'B', 'D', 'E'], ['E', 'E', 'E', 'A', 'E'], ['E', 'C', 'B', 'A', 'B']], [['B', 'A', 'C', 'E', 'D'], ['B', 'D', 'C', 'A', 'E'], ['B', 'B', 'B', 'B', 'E']]]
